[package]
name = "cherryrgb_cli"
version = "0.2.3"
edition = "2018"
publish = false

[workspace]

[dependencies]
cherryrgb = { path = "cherryrgb" }
anyhow = "1.0"
structopt = "0.3"
log = "0.4"
strum = "0.24.1"

[dependencies.simple_logger]
version = "1.13"
default-features = false
features = ["colors"]
