[package]
name = "cherryrgb_cli"
version = "0.1.0"
edition = "2018"

[workspace]

[dependencies]
cherryrgb = { path = "cherryrgb" }
anyhow = "1.0"
structopt = "0.3"
simple_logger = "1.13"
log = "0.4"
