[package]
name = "cherryrgb_cli"
version = "0.1.1"
edition = "2018"

[workspace]

[dependencies]
cherryrgb = { path = "cherryrgb" }
anyhow = "1.0"
structopt = "0.3"
log = "0.4"

[dependencies.simple_logger]
version = "1.13"
default-features = false
features = ["colors"]